#!/usr/bin/bash

UUID=`remarkable-cp $1 Sign-This-Doc`
ssh root@10.11.99.1 "systemctl restart xochitl"

FILENAME=`echo $1 | rev | cut -d. -f2- | rev`

while true
do
  read -p "Is the document signed?" -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    break
  fi
done

wget http://10.11.99.1/download/$UUID/placeholder -O "${FILENAME}.signed.pdf"
